baseURL = "https://hverhelst.github.io/"
languageCode = "en-us"
title = "Hugo Verhelst"
dateFormat = "January 2, 2006"


[params]
address = "Pavia, Italy"
email = "hugomaarten.verhelst@unipv.it"
firstName = "Hugo"
lastName = "Verhelst"
phone = ""
profileImage = "img/pasfotoTU.jpeg"
showQr = false
showContact = false
showSocializations = true

pages = ['defense']
sections = ["education","experience","awards","publications","conferences","software","teaching","supervision"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/hugo-verhelst/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/hverhelst/"
name = "GitHub"

[[params.handles]]
link = "https://orcid.org/0000-0001-8677-862X"
name = "ORCID"

[[params.handles]]
link = "https://scholar.google.com/citations?user=7cTDjzYAAAAJ&hl=en&oi=ao"
name = "Google Scholar"

[outputs]
home = ["HTML", "JSON"]

[markup.goldmark.renderer]
unsafe = true
