baseURL = "https://hugoverhelst.nl/"
languageCode = "en-us"
title = "Hugo Verhelst"
dateFormat = "January 2, 2006"


[params]
address = "Pavia, Italy"
email = "hugomaarten.verhelst@unipv.it"
firstName = "Hugo"
lastName = "Verhelst"
phone = ""
profileImage = "img/pasfotoTU.jpg"
showQr = false
showContact = false
showSocializations = true

pages = ['defense']
sections = ["education","experience","awards","publications","conferences","software","teaching","supervision"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
name = "LinkedIn"
link = "https://www.linkedin.com/in/hugo-verhelst/"
icon = "linkedin-in"

[[params.handles]]
name = "GitHub"
link = "https://github.com/hverhelst/"
icon = "github"

[[params.handles]]
name = "ORCID"
link = "https://orcid.org/0000-0001-8677-862X"
icon = "orcid"

[[params.handles]]
name = "Google Scholar"
link = "https://scholar.google.com/citations?user=7cTDjzYAAAAJ&hl=en&oi=ao"
icon = "google-scholar"

[[params.handles]]
name = "BlueSky"
link = "https://bsky.app/profile/hugoverhelst.nl"
icon = "bluesky"

[params.meta]
description = "Hugo Verhelst's personal website"
author      = "Hugo Verhelst"
favicon     = true

[outputs]
home = ["HTML", "JSON"]

[markup.goldmark.renderer]
unsafe = true
